# Generated by Django 4.2.30 on 2026-06-12 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(default=0.3)),
                ('auto_screenshot', models.BooleanField(default=True)),
                ('telegram_alerts', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=200)),
                ('chat_id', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('alert_cooldown_seconds', models.IntegerField(default=60)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Telegram Settings',
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(choices=[('live', 'Live Camera'), ('video', 'Video Upload')], max_length=10)),
                ('status', models.CharField(choices=[('violence', 'Violence Detected'), ('safe', 'No Violence')], max_length=10)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('video_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('violence_percentage', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
                ('violence_frames', models.IntegerField(blank=True, null=True)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
